<center><h1>Python Course</h1></center>
<center><h3>Iman Kahbasi</h3></center>
<center><h5>1402-02-13</h5></center>

<center><h2>Jupyter Notebook</h2></center>

User@PC-name:~/home$ jupyter-notebook 

<center><h2>google colab</h2></center>

https://colab.research.google.com

!pip install obspy

<center><h2>Matlab to Python</h2></center>

$f[1]$ or $f(1)$ ???

1) In Python, when making selections from objects such as lists, dictionaries, and strings, use square brackets to indicate the selection.

2) To call a function or method in Python, use parentheses.



Matlab: [1 2 3 4 5 6]

Python: [1, 2, 3, 4, 5, 6]

<center><h2>Variables</h2></center>

In Python, there are several types of variables:

1. Integer: An integer is a whole number, either positive or negative, without a decimal point. For example: `x = 5`

2. Float: A float is a number with a decimal point. For example: `y = 3.14`

3. String: A string is a sequence of characters enclosed in quotation marks. For example: `name = "Alice"`

4. Boolean: A boolean is a value that is either `True` or `False`. For example: `is_sunny = True`

5. List: A list is an ordered collection of elements enclosed in square brackets, where each element can be of any data type. For example: `numbers = [1, 2, 3]`

6. Tuple: A tuple is an ordered collection of elements enclosed in parentheses, where each element can be of any data type. However, unlike a list, a tuple is immutable, meaning it cannot be changed once it is created. For example: `coordinates = (3, 4)`

7. Dictionary: A dictionary is an unordered collection of key-value pairs enclosed in curly braces. Each key-value pair represents a mapping between the key and the value. For example: `person = {"name": "Bob", "age": 30}`

8. Set: A set is an unordered collection of unique elements enclosed in curly braces. For example: `unique_numbers = {1, 2, 3}`

Note that Python is a dynamically typed language, meaning that variables can change type during runtime. Therefore, the type of a variable is determined by the value it holds at a given time.

In [1]:
x = 42 # int()

y = 3.14 # float()

name = "AliCe" #str()

is_sunny = True

numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] # list()

coordinates = (3, 4) 

person = {"name": "Bob", "age": 30}

unique_numbers = {1, 2, 3, 3, 3, 3, 3, 3} # set

names_age = {"John": 25, "Jane": 30, "Bob": 35}

In [2]:
name == 'AliCe'

True

In [3]:
x = '3.14'
print(type(x))
x = float(x)
print(x+2)

<class 'str'>
5.140000000000001


In [28]:
a = [1, 2, 3, 3, 3, 3, 3, 3] # set
print(set(a))

{1, 2, 3}


<center><h2>making selections from objects such as lists, dictionaries, and strings, use square brackets</h2></center>

In [2]:
print(numbers[0])
print(numbers[-2])

1
9


In [5]:
print(name[0])
print(name[-2])

A
C


In [9]:
print(person['name'])

Bob


In [15]:
print(list(unique_numbers)[1])

2


In [29]:
print(numbers[1:5])

[2, 3, 4, 5]


In [31]:
print(numbers)
print(numbers[1:-2])

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[2, 3, 4, 5, 6, 7, 8]


In [37]:
print(numbers[1:9:2])

[2, 4, 6, 8]


In [ ]:
print(numbers[::2])

In [41]:
print(numbers[::-1])

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


In [42]:
numbers[2] = 999
print(numbers)

[1, 2, 999, 4, 5, 6, 7, 8, 9, 10]


In [43]:
numbers[2:5] = [999, 998, 997]
print(numbers)

[1, 2, 999, 998, 997, 6, 7, 8, 9, 10]


In [47]:
import numpy as np
arr = np.array(numbers)
print(type(arr))

<class 'numpy.ndarray'>


In [48]:
print(arr[0])
print(arr[-4:-1])

1
[7 8 9]


In [49]:
arr[np.array([False, False, True, False, False, False, False, False, False, False])]

array([999])

In [69]:
print(arr)
print(arr>20)

[  1   2 999 998 997   6   7   8   9  10]
[False False  True  True  True False False False False False]


In [92]:
msk = arr > 5
print(msk)

[False False False False False  True  True  True  True  True]


In [87]:
numbers.pop(1)
print(numbers)

[1, 8, 9, 10]


In [94]:
print(arr[~msk])

[1 2 0 0 0]


In [95]:
arr[msk] = 10
print(arr)

[ 1  2  0  0  0 10 10 10 10 10]


In [102]:
arr1 = np.arange(10)
arr2 = np.arange(40, 50)
print(arr1)
print(arr2)
#
msk = arr2 > 45
arr1[msk] = -999
print(f'{arr1=}')
print(arr2)

[0 1 2 3 4 5 6 7 8 9]
[40 41 42 43 44 45 46 47 48 49]
arr1=array([   0,    1,    2,    3,    4,    5, -999, -999, -999, -999])
[40 41 42 43 44 45 46 47 48 49]


In [103]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([[1, 2, 3, 4]])
print(arr1.shape, '\n', arr1)
print(arr2.shape, '\n', arr2)

(4,) 
 [1 2 3 4]
(1, 4) 
 [[1 2 3 4]]


In [104]:
print(arr1.T)

[1 2 3 4]


In [105]:
print(arr2.T)

[[1]
 [2]
 [3]
 [4]]


In [115]:
print(arr1.reshape((-1, 2)))

[[1 2]
 [3 4]]


In [120]:
arr3 = np.arange(100)
# print(arr3)
print(arr3.reshape(-1, 10))

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


<center><h2>Numpy vs List</h2></center>


In [122]:
l1 = [1, 2, 3]
l2 = [4, 5, 6]
print(type(l1))
print(l1+l2)

<class 'list'>
[1, 2, 3, 4, 5, 6]


In [123]:
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
print(a1+a2)

[5 7 9]


In [ ]:
def Func(x):
    return (x+2)**2

lst = []
for ii in range(10):
    a = Func(x=ii)
    lst.append(a)
print(lst)

In [ ]:
arr = np.zeros(10)
for ii in range(10):
    a = Func(x=ii)
    arr[ii] = a
print(lst)

In [ ]:
Func(np.arange(10))